services:
  app:
    container_name: gateway-service
    build:
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "8000:3000"
    volumes:
      - ./app/src:/usr/src/app/src
    networks:
      - microservices

networks:
  microservices:
    name: microservices
    driver: bridge