services:
  app:
    container_name: customer-service
    build:
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "8001:3000"
    volumes:
      - ./app:/usr/src/app
    networks:
      - microservices

networks:
  microservices:
    external: true