services:
  app:
    container_name: shopping-service
    build:
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "8003:3000"
    volumes:
      - ./app/src:/usr/src/app/src
    networks:
      - microservices

networks:
  microservices:
    external: true